spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG
s3:
  acesseKey: 2IG67RCV6USBARS20TXF
  secretKey: Ev+C30CEXBZS6Md3eUFIK24aE7z6r3xcNB01rjdw
  bucketName: movie-fun-course

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies

security:
    basic:
        enabled: false
